#
# mixer configuration
#
image: mixer

env:
  GODEBUG: gctrace=2

policy:
  enabled: true
  replicaCount: 1
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  cpu:
    targetAverageUtilization: 80
  podDisruptionBudget: {}
    # minAvailable: 1
    # maxUnavailable: 1

telemetry:
  enabled: true
  replicaCount: 1
  autoscaleEnabled: true
  autoscaleMin: 1
  autoscaleMax: 5
  cpu:
    targetAverageUtilization: 80
  podDisruptionBudget: {}
    # minAvailable: 1
    # maxUnavailable: 1
  sessionAffinityEnabled: false

podAnnotations: {}
nodeSelector: {}

adapters:
  kubernetesenv:
    enabled: true
  stdio:
    enabled: true
    outputAsJson: true
  prometheus:
    enabled: true
    metricsExpiryDuration: 10m
  # Setting this to false sets the useAdapterCRDs mixer startup argument to false
  useAdapterCRDs: true
