{{- if and .Values.autoscaleEnabled .Values.autoscaleMin .Values.autoscaleMax }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: istio-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ingress.name" . }}
    chart: {{ template "ingress.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  maxReplicas: {{ .Values.autoscaleMax }}
  minReplicas: {{ .Values.autoscaleMin }}
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: istio-ingress
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 80
{{ end }}
