apiVersion: v1
kind: Service
metadata:
  name: istio-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ingress.name" . }}
    chart: {{ template "ingress.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    istio: ingress
  annotations:
    {{- range $key, $val := .Values.service.annotations }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
{{- end }}
  type: {{ .Values.service.type }}
  selector:
    istio: ingress
  ports:
    {{- range $key, $val := .Values.service.ports }}
    -
      {{- range $pkey, $pval := $val }}
      {{ $pkey}}: {{ $pval }}
      {{- end }}
    {{- end }}
---
