{{- if or .Values.podDisruptionBudget .Values.global.defaultPodDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "ingress.name" . }}
    chart: {{ template "ingress.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    istio: ingress
spec:
{{- if .Values.podDisruptionBudget }}
{{ include "podDisruptionBudget.spec" .Values.podDisruptionBudget }}
{{- else if .Values.global.defaultPodDisruptionBudget }}
{{ include "podDisruptionBudget.spec" .Values.global.defaultPodDisruptionBudget }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "ingress.name" . }}
      release: {{ .Release.Name }}
      istio: ingress
{{- end }}
