- name: Get istio k8s install path
  set_fact:
    istio_k8s_dir: "{{ playbook_dir | dirname }}"

- name: Set istio definition pull path
  import_tasks: set_istio_distro_vars.yml

- name: Add istio bin dir to PATH
  import_tasks: add_to_path.yml
