#
# ingress configuration
#
enabled: false
autoscaleEnabled: true
autoscaleMin: 1
autoscaleMax: 5
# specify replicaCount when autoscaleEnabled: false
# replicaCount: 1
nodeSelector: {}

service:
  annotations: {}
  loadBalancerIP: ""
  type: LoadBalancer #change to NodePort, ClusterIP or LoadBalancer if need be
  #externalTrafficPolicy: Local #change to Local to preserve source IP or Cluster for default behaviour or leave commented out
  ports:
  - port: 80
    name: http
    nodePort: 32000
  - port: 443
    name: https
  selector:
    istio: ingress
