{{- if or .Values.podDisruptionBudget .Values.global.defaultPodDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-galley
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "galley.name" . }}
    chart: {{ template "galley.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    istio: galley
spec:
{{- if .Values.podDisruptionBudget }}
{{ include "podDisruptionBudget.spec" .Values.podDisruptionBudget }}
{{- else if .Values.global.defaultPodDisruptionBudget }}
{{ include "podDisruptionBudget.spec" .Values.global.defaultPodDisruptionBudget }}
{{- end }}
  selector:
    matchLabels:
      app: {{ template "galley.name" . }}
      release: {{ .Release.Name }}
      istio: galley
{{- end }}
