{{- range $key, $spec := .Values }}
{{- if or (eq $key "policy") (eq $key "telemetry") }}
{{- if $spec.enabled }}
{{- if or $spec.podDisruptionBudget $.Values.global.defaultPodDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: istio-{{ $key }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $key }}
    chart: {{ template "mixer.chart" $ }}
    heritage: {{ $.Release.Service }}
    release: {{ $.Release.Name }}
    version: {{ $.Chart.Version }}
    istio: mixer
    istio-mixer-type: {{ $key }}
spec:
{{- if $spec.podDisruptionBudget }}
{{ include "podDisruptionBudget.spec" $spec.podDisruptionBudget }}
{{- else if $.Values.global.defaultPodDisruptionBudget }}
{{ include "podDisruptionBudget.spec" $.Values.global.defaultPodDisruptionBudget }}
{{- end }}
  selector:
    matchLabels:
      app: {{ $key }}
      release: {{ $.Release.Name }}
      istio: mixer
      istio-mixer-type: {{ $key }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
