# This is used to generate istio.yaml with MCP enabled
global:
  # controlPlaneMtls enabled. Will result in delays starting the pods while secrets are
  # propagated, not recommended for tests.
  controlPlaneSecurityEnabled: false

  mtls:
    # Default setting for service-to-service mtls. Can be set explicitly using
    # destination rules or service annotations.
    enabled: false

  ## imagePullSecrets for all ServiceAccount. Must be set for any clustser configured with private docker registry.
  # imagePullSecrets:
  #   - name: "private-registry-key"

  # Default is 10s second
  refreshInterval: 1s

  useMCP: true


