# This is used to generate istio.yaml for minimal, demo mode.
# It is shipped with the release, used for bookinfo or quick installation of istio.
# Includes components used in the demo, defaults to alpha3 rules.

pilot:
  traceSampling: 100.0

grafana:
  enabled: true

tracing:
  enabled: true

servicegraph:
  enabled: true

kiali:
  enabled: true
