{{- if or .Values.podDisruptionBudget .Values.global.defaultPodDisruptionBudget }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: certmanager
  namespace: {{ .Release.Namespace }}
  labels:
    app: certmanager
    chart: {{ template "certmanager.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    version: {{ .Chart.Version }}
    {{- if .Values.podLabels }}
{{ toYaml .Values.podLabels | indent 4 }}
    {{- end }}
spec:
{{- if .Values.podDisruptionBudget }}
{{ include "podDisruptionBudget.spec" .Values.podDisruptionBudget }}
{{- else if .Values.global.defaultPodDisruptionBudget }}
{{ include "podDisruptionBudget.spec" .Values.global.defaultPodDisruptionBudget }}
{{- end }}
  selector:
    matchLabels:
      app: certmanager
      release: {{ .Release.Name }}
{{- end }}
