apiVersion: v1
name: istio-remote
version: 1.1.0
appVersion: 1.1.0
tillerVersion: ">=2.7.2"
description: Helm chart needed for remote Kubernetes clusters to join the main Istio control plane
keywords:
  - remote
sources:
  - http://github.com/istio/istio
engine: gotpl
icon: https://istio.io/favicons/android-192x192.png
