dependencies:
  - name: sidecarInjectorWebhook
    version: 1.1.0
    condition: sidecarInjectorWebhook.enabled
    repository: file://../subcharts/sidecarInjectorWebhook
  - name: security
    version: 1.1.0
    condition: security.enabled
    repository: file://../subcharts/security
  - name: gateways
    version: 1.1.0
    condition: gateways.enabled
    repository: file://../subcharts/gateways
  - name: istio-cni
    version: ">=0.0.1"
    repository: "@istio.io"
    condition: istio_cni.enabled
